# Generated by Django 4.2.1 on 2023-05-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='First',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wall_width', models.CharField(max_length=40)),
                ('room_width', models.CharField(max_length=40)),
                ('room_length', models.CharField(max_length=40)),
                ('room_height', models.CharField(max_length=40)),
                ('toilet_x_сoordinate', models.CharField(max_length=40)),
                ('toilet_y_сoordinate', models.CharField(max_length=40)),
                ('toilet_z_сoordinate', models.CharField(max_length=40)),
                ('shell_x_coordinate', models.CharField(max_length=40)),
                ('shell_y_coordinate', models.CharField(max_length=40)),
                ('shell_z_coordinate', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wall_width', models.CharField(max_length=40)),
                ('first_room_width', models.CharField(max_length=40)),
                ('first_room_length', models.CharField(max_length=40)),
                ('first_room_height', models.CharField(max_length=40)),
                ('toilet_x_сoordinate', models.CharField(max_length=40)),
                ('toilet_y_сoordinate', models.CharField(max_length=40)),
                ('toilet_z_сoordinate', models.CharField(max_length=40)),
                ('first_shell_x_coordinate', models.CharField(max_length=40)),
                ('first_shell_y_coordinate', models.CharField(max_length=40)),
                ('first_shell_z_coordinate', models.CharField(max_length=40)),
                ('second_room_width', models.CharField(max_length=40)),
                ('second_room_length', models.CharField(max_length=40)),
                ('second_room_height', models.CharField(max_length=40)),
                ('second_shell_x_coordinate', models.CharField(max_length=40)),
                ('second_shell_y_coordinate', models.CharField(max_length=40)),
                ('second_shell_z_coordinate', models.CharField(max_length=40)),
                ('bath_x_сoordinate', models.CharField(max_length=40)),
                ('bath_y_сoordinate', models.CharField(max_length=40)),
                ('bath_z_сoordinate', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='third',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wall_width', models.CharField(max_length=40)),
                ('room_width', models.CharField(max_length=40)),
                ('room_length', models.CharField(max_length=40)),
                ('room_height', models.CharField(max_length=40)),
                ('toilet_x_сoordinate', models.CharField(max_length=40)),
                ('toilet_y_сoordinate', models.CharField(max_length=40)),
                ('toilet_z_сoordinate', models.CharField(max_length=40)),
                ('shell_x_coordinate', models.CharField(max_length=40)),
                ('shell_y_coordinate', models.CharField(max_length=40)),
                ('shell_z_coordinate', models.CharField(max_length=40)),
                ('bath_x_сoordinate', models.CharField(max_length=40)),
                ('bath_y_сoordinate', models.CharField(max_length=40)),
                ('bath_z_сoordinate', models.CharField(max_length=40)),
                ('x_room_curvature_coordinate', models.CharField(max_length=40)),
                ('y_room_curvature_coordinate', models.CharField(max_length=40)),
            ],
        ),
    ]
